### PR TITLE
Refactor installation code

### LINKED ISSUE #19: Cron job to clean up old and/or broken desktop files
*Related to #18.*

In #18, it is suggested to add `TryExec` keys to integrated desktop files to have launchers hide them if the files are not in place, to prevent users from using launchers that won't work.

However, this might lead to "broken" desktop files in the user's `$XDG_DATA_HOME/application` directory, which are, unlike with appimaged, never cleaned up. Therefore, we should add a cron job to the packages built by this project that takes care of cleaning up such files in the users' home directories.

Questions:

  - Can the cron job be user-specific? If it can't, we will have to set up a system wide cron job that then needs to be written with extra care so that it won't delete files it shouldn't with root permissions.
  - How often shall the cron job be run?
    - Running it too often might slow down the system. See https://github.com/AppImage/AppImageKit/issues/744 etc.
    - I think a daily cleanup should suffice. Desktop files are tiny, and shouldn't bloat the home directory horribly.

### PR DESCRIPTION
**Pull request by TheAssassin**
Extracted code from the maintainer scripts to a central script to
avoid duplicate code.

Added support for systemd-binfmt with a binfmt.d config for distros
without binfmt-support packages.

Fixes #19

### CODE REVIEW

**Comment by NuLogicSystems** [comment]
The debian binfmt-support package actually uses it's own systemd service:
/lib/systemd/system/binfmt-support.service
/etc/init/binfmt-support.conf
https://packages.debian.org/en/sid/amd64/binfmt-support/filelist

So, if this package is installed it will use that.

**Comment by TheAssassin** [comment]
@NuLogicSystems that file just enables or disables the whole binfmts support entirely, apparently. I'm furthermore not 100% sure whether it loads the binfmt.d config files, and doesn't just read the `/var/lib/binfmts` files.

**Comment by NuLogicSystems** [comment]
Yea, that makes sense if it follows the normal systemd config file hierarchy actually.

**Comment by TheAssassin** [comment]
@NuLogicSystems I merged the PR for now, as it contains a few fixes, and doesn't break with the existing integration methods. I'll test the whole thing with the AUR PKGBUILD on Manjaro now, to see whether the integration works now.

**Comment by NuLogicSystems** [comment]
Did you already fix the pre >> post uninstall issue?

**Comment by TheAssassin** [comment]
Ah, crap! I forgot to push that commit. I'll fix that immediately. Thanks.

**Comment by NuLogicSystems** [comment]
Building it now on my Enlightenment system.

**Comment by NuLogicSystems** [comment]
I pushed a commit to AUR removing the old install file.

**Comment by NuLogicSystems** [comment]
The default pacman hook for Registering binary formats works, however Registering binary formats does not run after uninstall. We may need to add an post_remove hook for our package.

**Comment by NuLogicSystems** [comment]
OK, /usr/share/libalpm/hooks/systemd-binfmt.hook only has Install and Upgrade as operations.
Maybe I can get the maintainer to add Remove, otherwise my first though applies.

**Comment by TheAssassin** [comment]
Did you try to manually call this hook after uninstalling? Did it clean up the integration?

**Comment by NuLogicSystems** [comment]
No the hook needs an Operation=Remove line for that to work.

**Comment by TheAssassin** [comment]
I meant like "do whatever the hook does" (like me calling `systemd restart systemd-binfmt` on Ubuntu). Then, check whether AppImages can be executed "normally", or whether any call to an AppImage will fail because the interpreter is no longer available on the system.

**Comment by NuLogicSystems** [comment]
Yes, that is basically what the hook does: systemd restart systemd-binfmt

**Comment by TheAssassin** [comment]
You didn't reply to my actual question: does it re-enable "normal" AppImage execution? In my tests on Debian/Ubuntu, it didn't work.

**Comment by NuLogicSystems** [comment]
I've never had an issue with appimages running if the exec bit is enabled on arch.

**Comment by TheAssassin** [comment]
That's a critical issue.

**Comment by NuLogicSystems** [comment]
So yes, it is working.

**Comment by TheAssassin** [comment]
@NuLogicSystems You need to be a bit more elaborate, I think I'm missing your point.

Let's recapitulate:

If we set up binfmt support with such a config file, on installation, the format is registered in the kernel, and AppImageLauncher is called when (executable!) AppImages are executed.

Now, we want to remove the package. We restart this service, like the hook would do (doesn't matter if it's in the `post_remove` hook yet).

Expected behavior: kernel format is unregistered, AppImages can be executed, they launch normally.

Actual behavior (on Debian): Launching does no longer work. Expected problem: format is still registered, the "restart" didn't unregister it, but the interpreter is missing, therefore the call fails.

Actual behavior (on Arch): ?

**Comment by NuLogicSystems** [comment]
OK, well after install AppImageLauncher is not called, the appimages run as normal.
If I run AppImageLauncher *.appimage i'm getting:
Failed to clean up old desktop files

**Comment by NuLogicSystems** [comment]
Does this work as intended under rpm based?

**Comment by TheAssassin** [comment]
I'll re-check, let me quickly boot some openSUSE.

**Comment by NuLogicSystems** [comment]
The reason I ask is our conf file looks much different than the others I've looked at.

**Comment by TheAssassin** [comment]
Check https://www.freedesktop.org/software/systemd/man/binfmt.d.html for more information. The configuration file adheres to the format referred on this page, https://www.kernel.org/doc/Documentation/admin-guide/binfmt-misc.rst.

**Comment by NuLogicSystems** [comment]
Ours:
:appimage-type2:M:8:414902::/usr/bin/AppImageLauncher:
Others:
:Java:M::\xca\xfe\xba\xbe::/usr/bin/javawrapper:
:Applet:E::html::/opt/java/bin/appletviewer:
:Java:M::\xca\xfe\xba\xbe::/usr/bin/javawrapper:

:CLR:M::MZ::/usr/bin/mono:

**Comment by NuLogicSystems** [comment]
Please let me know how suse goes.

**Comment by NuLogicSystems** [comment]
If I use the old package from the repository I don't get the error.

**Comment by TheAssassin** [comment]
What error?

I am referring to an installation bug "directory conflict", CMake's auto generated file list often includes empty directories, which is not a problem with Debian packages, but with RPM packages. Hence I added it to the exclude list I maintain.

**Comment by NuLogicSystems** [comment]
The Failed to clean up old desktop files i'm getting with AppImageLauncher *.appimage.

**Comment by TheAssassin** [comment]
I can reproduce the bug now with the official packages. I'll have a look.

**Comment by NuLogicSystems** [comment]
Still, I don't know why it's not trying to launch with the interpereter when executing the aiimage files by themselves. But one thig at a time. ;)

**Comment by TheAssassin** [comment]
The function is `bool` but didn't return, probably undefined behavior. I added an explicit `return true` statement, `return false` isn't used in the function (yet), so I hope this fixes the issue.

**Comment by TheAssassin** [comment]
@NuLogicSystems works now.

**Comment by NuLogicSystems** [comment]
That does, no more error.
But running just the appimage by itself is still not using the launcher.

**Comment by TheAssassin** [comment]
What system? How can I reproduce the issue?

**Comment by NuLogicSystems** [comment]
Netrunner Rolling

**Comment by NuLogicSystems** [comment]
This works:
`:appimage-type2:E::AppImage::/usr/bin/AppImageLauncher:
`

**Comment by TheAssassin** [comment]
@NuLogicSystems this only uses the extension, and isn't reliable at _all_. We need the magic bytes check.

So far I can tell that the registration itself works, calling `cat /proc/sys/fs/binfmt_misc/appimage-type2` yields a description of the format I defined.

Looking at the contents, though, I found the issue:
screenshot_2018-04-26_23-27-03

The `magic` description is wrong. I think I know how to fix it. Give me a minute or two, please.

**Comment by TheAssassin** [comment]
Fixed, @NuLogicSystems.

**Comment by NuLogicSystems** [comment]
BTW, in the interum since using my /etc/binmft.d/appimage.conf file was working.
I ran systemd restart systemd-binfmt after I uninstalled the package and deleted my file, normal function for appimages was restored.

**Comment by NuLogicSystems** [comment]
Rebuilding from AUR now.

**Comment by TheAssassin** [comment]
Good to know. Nevertheless, your file was only relying on the extension, which is unreliable for various reasons. Some AppImages ship without extension. And, technically, an extension on unix-ish platforms is merely a form of decorating the filename, but nothing technically necessary.

**Comment by NuLogicSystems** [comment]
Thanks for that. Been using Linux since 1995, before that i used Minux, AIX, 4.4BSD + (actually still use freeBSD), SunOS (Solaris), System V.

**Comment by NuLogicSystems** [comment]
Yes, success. Launched the appimage with appimagelauncher this time.

**Comment by NuLogicSystems** [comment]
And uninstalling the pakage and running systemctl restart systemd-binfmt restores normal function.

We have a winner.. Yeahhhh.

**Comment by TheAssassin** [comment]
@NuLogicSystems thanks for your help. I did by the way not try to lecture you, but I write my comments in a way that future readers who don't know about a fact will understand it completely, therefore I tend to be more elaborate in my replies than the average GitHub user. I'm just glad we have a working Arch setup now... was way more work than for any other distro...

**Comment by NuLogicSystems** [comment]
I didn't think you were lecturing me. It just inadvertantly made me feel  bit old, not your fault. ;)

**Pull request merged**
