### PR TITLE
Update BUILD.md with Ubuntu 23.10 build instructions

### PR DESCRIPTION
**Pull request by lxe**
Had to install a few more things to get it to work on Ubuntu 23.10

### CODE REVIEW

**Comment by TheAssassin** [comment]
Thanks.

**Comment by TheAssassin** [comment]
You shouldn't have to do this, obviously. There is an install target. It might be enabled only with the official packages, though. One should not just `sudo make install` software anyway.

**Comment by lxe** [comment]
I wanted to build it from scratch since there were no debs built via CI in the ppa's for Ubuntu 23. This worked like a charm tough. Thank you for this software!

**Comment by TheAssassin** [comment]
You can use the build scripts to generate your own `.deb`s if you want to, they at least take care of installing and uninstalling everything properly. The same `.deb`s can be found on the GitHub release page.

**Pull request merged**
