### PR TITLE
Put into Settings category and do not have Settings in the name

### PR DESCRIPTION
**Pull request by probonopd**
Makes it consistent with other settings

### CODE REVIEW

**Comment by TheAssassin** [comment]
Changing categories seems like a good idea. But I'd like to keep `Settings` in the name; if you use the search there should be some hint that this belongs to the control panel. Try on e.g., Kubuntu, you'll know what I mean (there'll be tons of entries from the desktop actions, finding the right one is easy if you can type `AppImageLauncher settings`).

**Comment by probonopd** [comment]
Please do not put "Settings" into the name as none of the other ones have "Settings" in their name. We can have "settings" in the description or keywords, though.

**Comment by TheAssassin** [comment]
> Please do not put "Settings" into the name as none of the other ones have "Settings" in their name. We can have "settings" in the description or keywords, though.

"LightDM Greeter settings"... "CompizConfig Settings Manager"...  "Light Locker Settings"... everything non-system has "settings" in it, on my and on most other systems. Your own screenshot shows this.

**Comment by probonopd** [comment]
> everything non-system 

We want to look native. What do you think about my proposal to put settings into keywords and/or description? Would that work for your use case (search)?

**Comment by TheAssassin** [comment]
That doesn't have anything to do with "nativeness". AppImageLauncher, like other software, is not part of the desktop environment. And the word "AppImageLauncher" is misleading in that title. Period.

**Comment by probonopd** [comment]
"Settings -> AppImage desktop integration"?

**Comment by probonopd** [comment]
Thank you.

**Pull request merged**
