### PR TITLE
Created ui.zh_TW.ts

### PR DESCRIPTION
**Pull request by olivertzeng**
temporary

### CODE REVIEW

**Comment by TheAssassin** [comment]
***Please stop opening new pull requests.*** The notifications are annoying, and you're increasing the pull request/issue counter for no reason.

If you need to practice, create your own repository.

Please learn how to use Git, as you seem to use the annoying Web interface only.

**Comment by olivertzeng** [comment]
no I mean i wanna sqash and merge lol

**Comment by olivertzeng** [comment]
but how?

**Comment by olivertzeng** [comment]
thanks

**Comment by olivertzeng** [comment]
Lol, if the proccess is that hard, i would rather not use this product and just don't ever touch appimage ever again

**Comment by olivertzeng** [comment]
gonna leave it alone

**Pull request closed without merging**
