### PR TITLE
Update libappimage

### PR DESCRIPTION
**Pull request by azubieta**
Include fix for #212

### CODE REVIEW

**Comment by TheAssassin** [comment]
This surely won't be merged before all remaining version 2.0 issues are resolved.

**Comment by azubieta** [comment]
I see a deadlock here: this fix will not be merged until the [milestone 2](https://github.com/TheAssassin/AppImageLauncher/milestone/2) is completed and the issues remaining for that milestone were blocked by @probonopd [here](https://github.com/TheAssassin/AppImageLauncher/issues/212#issuecomment-515804545)

**Comment by probonopd** [comment]
Then we need to roll back to what we had ~3 weeks ago when it was still working. Because what is out there currently is broken...

**Comment by probonopd** [comment]
My personal development philosophy is "life is too short to maintain anything than master". But the flip-side of that is, "i am using master all the time myself, and if something breaks master, it is reverted immediately"...

**Comment by TheAssassin** [comment]
Plan is now to just fix the remaining issues to make a stable release that contains AppImageLauncher Lite. Once that is done, we focus on 2.x again.

**Comment by TheAssassin** [comment]
Regarding #212, that's likely not fixing the issue. Issues started when that restart code @azubieta wrote was merged. Before, everything was fine. Therefore my suspicion is the whole thing crashes when that timer code is run.

**Comment by azubieta** [comment]
I ran gdb on the broken binaries and it took me to an internal function in `libappimage`. Therefore I updated the libappimage version that was being used. Build it on travis and test the results in a live system (were the broken version was in fact broken) and it worked fine. That's why I say that this solve that issue.

**Comment by TheAssassin** [comment]
@azubieta then please provide some binaries for me to reproduce the issue. I have plenty AppImages, but I cannot reproduce the issue.

**Comment by azubieta** [comment]
You will need new  (un-integrated) binaries. A live system will do too, the binaries I used were:

appimagelauncherd: https://github.com/TheAssassin/AppImageLauncher/releases/download/continuous/appimagelauncher-lite-1.3.1-x86_64.AppImage

applications: 
https://www.appimagehub.com/p/1314336
https://www.appimagehub.com/p/1309781/
https://www.appimagehub.com/p/1308712/

**Comment by TheAssassin** [comment]
Thanks for sharing, will try soon-ish. Btw, `touch`ing also works to re-integrate existing binaries.

**Comment by TheAssassin** [comment]
> appimagelauncherd: https://github.com/TheAssassin/AppImageLauncher/releases/download/continuous/appimagelauner-lite-1.3.1-x86_64.AppImage

That version doesn't even install, due to a bug in the script it seems (doesn't create `user` subdir for systemd unit installation). I wonder how _you_ could test that...

**Comment by azubieta** [comment]
I manually created the directories, not big deal.

**Comment by TheAssassin** [comment]
> I manually created the directories, not big deal.

Next time please don't hesitate to open new issues, I wasn't aware of those issues and that might've put down potential users from using this software.

> Also you can run it without installing it.

True, haven't thought of that.

**Comment by TheAssassin** [comment]
So, you're right @azubieta, the issue will likely be solvable with upgrading libappimage. But still, that's not possible as of now.

**Pull request merged**
