### PR TITLE
Fix wording, closes #190

### LINKED ISSUE #190: Remove fails if AppImage location is not user writeable
removefail

If AppImage location is not user writeable, the user should be asked for root credentials if needed. Check https://github.com/antony-jr/AppImageUpdater/blob/ff85721bf285a7483fada6c4aed0ee79884da482/AuthorizationDialog.cc.

### PR DESCRIPTION
**Pull request by probonopd**

### CODE REVIEW

**Comment by TheAssassin** [comment]
You cannot just change these auto-generated files in order to change wording.

Also your changes are de facto wrong. This trash bin directory mentioned for instance is not the global trash. It's something entirely different, something special to AppImageLauncher. I explained it in more detail before, so I'm not going to repeat myself here again.

**Comment by probonopd** [comment]
Please change `Failed to move AppImage into trash bin directory` to `Could not move to Trash`. The user (nor I) don't care about what a "trash bin directory" is. I also don't want to have it explained. I want it to just do what I as the user expect it to do, "move it to the Trash".

> This trash bin directory mentioned for instance is not the global trash. It's something entirely different, something special to AppImageLauncher.

Then let's change it and let's use the normal trash the user knows and loves.

**Comment by TheAssassin** [comment]
Since you're not interested in the reasons: ***No, that's not going to work, that won't happen as it would break!***

It's an error that is caused by not elevating permissions. So, the fix for this is, elevate permissions if necessary. Even then this message is needed to catch the other potential "cannot move" issues.

Why do *you* pretend to be annoyed even? I am a fan of the era of Enlightenment. I don't mind explaining details. But I am getting annoyed by people who tell me they aren't interested and then do random things or make random assumptions that cause me more work than if they just let me do it.

**Comment by probonopd** [comment]
I am trying to anticipate the user experience normal "mere mortal" users are going to have.
They know what Trash is, they don't know anything else, and they will never be interested in learning about the difference of the Trash they know vs. a "trash bin directory" that works differently.

**Comment by TheAssassin** [comment]
They don't have to *know* what went wrong if that error occurs, they should actually open issues here, since this issue is likely a bug. In this case, it also is, we don't have that elevate permissions thing. Once we have that, your use case is going to work, too.
If that issue  ever happens, we *want* user reports and complaints. It's the only way to get feedback about bugs after all.

**Comment by probonopd** [comment]
Complicated wording "mere mortals" do not understand gives the impression of software being "technical" and "complicated", not "enjoyable" and "easy". Messages are not written for the developer of the software, but for the user of the software.

**Comment by TheAssassin** [comment]
Either the message is precise, or it's *really* abstract. Either way is fine. But for the latter you then need a fail safe way to resolve the "abstract" message to the point in the source code. We could introduce error codes.

**Comment by probonopd** [comment]
"Cannot delete"

**Comment by TheAssassin** [comment]
There's more than one message to replace that'd go like "cannot delete" if we decide to go into a more polished, abstracted direction.

**Pull request closed without merging**
