### PR TITLE
Show AppImageLauncher settings in XFCE

### PR DESCRIPTION
**Pull request by koyuawsmbrtn**
This makes the AppImageLauncher settings show up in the XFCE control panel

### CODE REVIEW

**Comment by TheAssassin** [comment]
Now I'm curious? What version of XFCE are you using? I use the one on xubuntu 18.04 (up to date), and I can see the settings in the control panel.

I'm not opposed to adding more categories, but I'll have to check their meaning.

**Comment by TheAssassin** [comment]
`DesktopSettings;LXQt;` looks unrelated, what's their purpose?

**Comment by koyuawsmbrtn** [comment]
> `DesktopSettings;LXQt;` looks unrelated, what's their purpose?

LXQT also offers to have .desktop files in the control panel and DesktopSettings is here for compatibilty reasons. I just merely copy and pasted the categories found from the Kvantum settings item.

> Now I'm curious? What version of XFCE are you using? I use the one on xubuntu 18.04 (up to date), and I can see the settings in the control panel.
> 
> I'm not opposed to adding more categories, but I'll have to check their meaning.

It doesn't work for me and I'm running Xubuntu 18.04 as well

**Comment by TheAssassin** [comment]
I'm not opposed at all to merging this, the opposite is true. Thanks for helping out!

But I would like to understand the different behavior. Have you checked your "Other" area? For me, it looks like this:

screenshot_2020-05-10_20-40-52

We anyway have some time until the CI is satisfied (which it will be, of course).

**Comment by koyuawsmbrtn** [comment]
Funnily enough this resides in my "Personal" section of the control panel

image

**Comment by TheAssassin** [comment]
Yeah, probably now after these changes. Anyway, there is no reason not to do so, so let's just merge them. Thanks!

**Comment by TheAssassin** [comment]
> Funnily enough this resides in my "Personal" section of the control panel

I mean, that comes from that `X-XFCE-PersonalSettings` obviously...

**Pull request merged**
