### PR TITLE
Insert missing space into text String

### PR DESCRIPTION
**Pull request by claell**
I am not familiar with handling translations, but only found the occurrence in the translation files. So I just changed it for the English translation, however the root of the text might be somewhere else.

### CODE REVIEW

**Comment by TheAssassin** [comment]
Thanks for the hint, but your PR has a few problems. First of all, you changed the source files, that won't make any difference, it'll just invalidate that string.
Second there's that second `up` is superfluent, it should be removed at all. That has to be done in all files.

Translations are handled in https://translate.assassinate-you.net/projects/appimagelauncher/ui/
This however is a source code issue, and we can't fix it there either.

I'll close your PR and will fix it the right way, thanks again for the hint.

**Comment by claell** [comment]
> Translations are handled in https://translate.assassinate-you.net/projects/appimagelauncher/ui/

This is where I came across it.

> Second there's that second `up` is superfluent, it should be removed at all.

Alright, thought the same at first.

Thanks for fixing it in all files. Is it normal that the old lines remain untouched in the English file and only new lines are added to it?

**Comment by TheAssassin** [comment]
Yeah, sometimes old translations are kept for some reason, sometimes Qt linguist deletes them. I'm not an expert there. I didn't even find that string in the source code any more, but for good style I just fixed the translation files and re-ran the translation commands over there. That also updated some other things.

**Comment by claell** [comment]
Ah ok. So probably this is outdated anyway which also explains why I did not find any occurrence in the source code, but only the translation files when searching for it in this repo.

**Comment by TheAssassin** [comment]
Yeah, I thought so too. I guess I should've asked for your version.

**Comment by claell** [comment]
Version does not matter here, I just came across this issue when looking around on the site for translations.

**Pull request closed without merging**
