### PR TITLE
Monitor mounted filesystems

### LINKED ISSUE #154: [appimagelauncherd] Monitor and integrate (w/o moving) AppImages in Applications dir on all mounted directories
See title. Might come in handy for @probonopd's way of using Linux.

### PR DESCRIPTION
**Pull request by TheAssassin**
Fixes #154.

You can switch on this feature by calling appimagelauncherd with the flag `--monitor-mounted-filesystems`. We could also make this a setting at some point.

@probonopd please try out the feature ASAP, as you requested it. This is a pretty new and right now experimental feature that requires some testing. But once I'm completely done with the remaining tasks, we can release the first beta for 2.0.0.

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks @TheAssassin, going to test https://artifacts.assassinate-you.net/artifactory/AppImageLauncher/travis-808/appimagelauncher-lite-2.0.0-alpha-2-travis808-567ce44-x86_64.AppImage now.

**Comment by probonopd** [comment]
I do not know how to get `--monitor-mounted-filesystems` into the systemd launcher file because I am using `/appimagelauncher-lite.AppImage install` each time the system boots (using SystemImageKit). I think it would be much easier (and also much more logical) if we could do

```
[AppImageLauncher]
ask_to_move=false
enable_daemon=true
monitor_mounted_filesystems=true
```

**Comment by probonopd** [comment]
```
me@host:~$ systemctl --user stop appimagelauncherd
me@host:~$ nano ./.local/lib/appimagelauncher-lite/systemd/appimagelauncherd.service
# changed the line to read:
# ExecStart=/home/me/.local/lib/appimagelauncher-lite/appimagelauncher-lite.AppImage appimagelauncherd --monitor-mounted-filesystems
me@host:~$ systemctl --user daemon-reload
me@host:~$ systemctl --user start appimagelauncherd
```

Does __not__ work for me.

```
● appimagelauncherd.service - AppImageLauncher daemon
   Loaded: loaded (/home/me/.local/lib/appimagelauncher-lite/systemd/appimagelauncherd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2019-10-13 10:44:30 CEST; 2min 1s ago
 Main PID: 2664 (appimagelaunche)
   CGroup: /user.slice/user-999.slice/user@999.service/appimagelauncherd.service
           ├─2664 /tmp/.mount_appimaOZLhTC/usr/bin/appimagelauncherd
           └─2668 /home/me/.local/lib/appimagelauncher-lite/appimagelauncher-lite.AppImage appimagelauncherd

Oct 13 10:44:30 host systemd[1749]: Started AppImageLauncher daemon.
Oct 13 10:44:30 host appimagelauncher-lite.AppImage[2664]: Searching for existing AppImages
Oct 13 10:44:30 host appimagelauncher-lite.AppImage[2664]: Searching directory: /home/me/Applications
Oct 13 10:44:30 host appimagelauncher-lite.AppImage[2664]: Watching directories: /home/me/Applications
Oct 13 10:44:42 host systemd[1749]: appimagelauncherd.service: Current command vanished from the unit file, execution of the command list won't be resumed.
```

It does not pick up `/isodevice/Applications` where all my AppImages reside.

```
me@host:~$ mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=5017632k,nr_inodes=1254408,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=1010092k,mode=755)
/dev/sda1 on /isodevice type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/loop0 on /cdrom type iso9660 (ro,noatime,nojoliet,check=s,map=n,blocksize=2048)
/dev/loop1 on /rofs type squashfs (ro,noatime)
/cow on / type overlay (rw,relatime,lowerdir=//filesystem.squashfs,upperdir=/cow/upper,workdir=/cow/work)
/dev/sda1 on /isodevice type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
```

**Comment by probonopd** [comment]
Most strangely, running `/home/me/.local/lib/appimagelauncher-lite/appimagelauncher-lite.AppImage appimagelauncherd --monitor-mounted-filesystems` by hand in the terminal __does__ work. The last line says: `Watching directories: /home/me/Applications /isodevice/Applications`. What is going on? Is systemd playing a trick on me?

**Comment by TheAssassin** [comment]
Please provide the output of `--list-watched-directories` both in combination with the other flag and without. This will show us what directories are monitored. As said, the code to detect the additional locations isn't tested very well so far, as your scenario kind of differs from e.g., a VM.

**Comment by probonopd** [comment]
Can we please have

```
[AppImageLauncher]
monitor_mounted_filesystems=true
```
?

**Comment by TheAssassin** [comment]
I will make this an option after my tests have been finished and this PR has been merged.

**Comment by TheAssassin** [comment]
Now, the case when a formerly watched directory disappeared (e.g., when a USB stick has been unplugged) is handled properly. The old entries are cleaned up as soon as we notice the directory is gone. These last changes complete this new feature pretty much in my opinion. When the builds succeed, I'll test the produced binaries, and when my tests are successful, I'll merge the PR and prepare for the first beta of the new AppImageLauncher 2.0.0.

**Comment by TheAssassin** [comment]
Travis took really long to build the binaries, but from my tests everything works as expected.

**Comment by probonopd** [comment]
Great to hear @TheAssassin. Is there an ETA yet for 

> We could also make this a setting at some point.

**Comment by TheAssassin** [comment]
There *is* a setting. Check https://github.com/TheAssassin/AppImageLauncher/blob/master/src/shared/shared.cpp#L157. See https://github.com/TheAssassin/AppImageLauncher/commit/a67bc8fb7bdd4151cd94f2d6b7ec1109e76901ff for more information.

**Pull request merged**
